name: sp_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libcblas=3.11.0=4_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran=15.2.0=h69a702a_15
  - libgfortran5=15.2.0=h68bc16d_15
  - libgomp=15.2.0=he0feb66_15
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.46.0=py310hee1c697_0
  - ncurses=6.5=h2d0b736_3
  - numba=0.63.1=py310h225f558_0
  - numpy=1.26.4=py310hb13e2d6_0
  - openssl=3.6.1=h35e630c_1
  - python=3.10.19=h3c07f61_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_ha0e22de_103
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - anndata==0.10.9
      - array-api-compat==1.13.0
      - asciitree==0.3.3
      - asttokens==3.0.1
      - astunparse==1.6.3
      - cachetools==6.2.4
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - contourpy==1.3.2
      - csbdeep==0.8.2
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fasteners==0.20
      - fire==0.7.1
      - flatbuffers==25.9.23
      - fonttools==4.61.1
      - gast==0.7.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - ipykernel==7.1.0
      - ipython==8.37.0
      - jedi==0.19.2
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - keras==2.15.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - ml-dtypes==0.3.2
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numcodecs==0.13.1
      - oauthlib==3.3.1
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - pip==26.0.1
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pygments==2.19.2
      - pympler==1.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==82.0.0
      - six==1.17.0
      - stack-data==0.6.3
      - stardist==0.9.2
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wheel==0.46.3
      - wrapt==1.14.2
      - xarray==2025.6.1
      - zarr==2.18.3
prefix: sp_env
